### ISSUE TITLE
No button for "show all Notifications"

### ISSUE THREAD

**Issue by john-kheir** [freeflowpages/freeflow-android#1]
**No button for "show all notifications" .. Even when you get it from the bell icon and click it, no notifications will be shown.**

#### Android version: 8.1

![issue](https://user-images.githubusercontent.com/15011431/54692181-3f5a3a00-4b2d-11e9-8568-1280f8a9cbe8.png)

**Comment by Hamdy** [comment]
Jimber guys working on new app any ways, so no need for this
