### ISSUE TITLE
Pictures can be seen through the web but not through the app.

### ISSUE THREAD

**Issue by john-kheir** [freeflowpages/freeflow-android#4]
This issue happens with all users and iit can be seen in the user pages and in the dashboard pages
## Picture can be seen on the web

![web2](https://user-images.githubusercontent.com/15011431/55066725-010dcf00-5087-11e9-99a4-fc29a70df1b8.png)

## Same Picture can't be seen on the app

![mobile1](https://user-images.githubusercontent.com/15011431/55066730-03702900-5087-11e9-956b-ff5f8fd05343.png)

**Comment by Hamdy** [comment]
Jimber guys working on a mobile app, so no need for this now
