### ISSUE TITLE
Can't maximize youtube video

### ISSUE THREAD

**Issue by john-kheir** [freeflowpages/freeflow-android#5]
**Can't maximize youtube video when clicking on the maximize button (which is in red rectangle in the following photo)**

### Android Version: 8.1

![youtube](https://user-images.githubusercontent.com/15011431/55081986-86a27680-50a9-11e9-819d-b870a43b0dfe.png)

**Comment by Hamdy** [comment]
Jimber guys are working on new mobile app.
no need to work on this now
