### ISSUE TITLE
Can't upload pictures more than 2 MB

### ISSUE THREAD

**Issue by john-kheir** [freeflowpages/freeflow-android#7]
![big-size](https://user-images.githubusercontent.com/15011431/55287124-27907a80-53a5-11e9-9642-d0e5bff3a385.png)

**Comment by Hamdy** [comment]
Hard limit on file uploads is now 50MBs
however we force a soft limit for all uploads to be 2MBs only for performance reasons
we can increase that later if needed, but up to now, we prefer small file sizes
